### ISSUE TITLE
Toolbar Situation

### ISSUE THREAD

**Issue by parshav** [ServerDriven/ScreenData#20]
Toolbar on a screen requires more than just a title, like color/menu items. In some cases it could be hidden entirely. Should we have a toolbar object in SomeScreen or just another attribute for toolbar color for now, and figure out a different theme solution.

**Comment by 0xLeif** [comment]
I'll defer to what you suggest as I have not had an issue with this or have just ignored it with workarounds. My main questions are...

- Does it make sense to have in ScreenData or should it be an iOS/ Android specific implementation? I.E. Static overrides
- This could also cause issues... for example, in iOS, if we have a screen that is a  modal... it doesn't have a Top Nav/ Toolbar... So the Title of that screen is not used... If that screen has a destination... Then the problem will continue if the destination screen has a toolbar...
- I could see Toolbar being part of a new type called ScreenStyle... but that wouldn't always guarantee that the Toolbar will be presented! BUT! It could guarantee that it is hidden or styled correctly when shown.

**Comment by parshav** [comment]
Thats where i think if there's a theme mechanism, then the toolbar can automatically inherit from a preset theme, which would be something like the static implementation, although at some point it would be nice to be server driven as well ! like a `/api/theme` endpoint. 
If the destination has a modal type, the toolbar could remain hidden to account for that too, right now the destination only points it to another screen, we do not specify the type of screen.

**Comment by 0xLeif** [comment]
I really like the theme idea... I already have a defaultForegroundColor for SDImage.. https://github.com/ServerDriven/ScreenDataUI-ios/blob/005567ccd2db04793e12c9a66d346c8cffab84f0/Sources/ScreenDataUI/Views/SDImage.swift#L12

I don't have a preference right now if that Theme object comes down from an endpoint or is attached to a screen.. This might also be the time to have the SDApp object wrap the screens.. 

> right now the destination only points it to another screen, we do not specify the type of screen.

We should probably add Modal/ Sheet as a type of screen.. This will get difficult with SwiftUI though.. Right now I have treated any modal screen as a known modal screen... Meaning that in the app it is setup to be a sheet with a specific SDScreen... Might need to chat about these changes tonight or tomorrow!

**Comment by 0xLeif** [comment]
stale
